### ISSUE TITLE
Pretraining and optimizing parameters issues

### ISSUE THREAD

**Issue by Markin-Wang** [yaoyao-liu/E3BM#4]
Hi, thanks for sharing your excellent work.
I am trying to pretrain the model in my own dataset and an error occurs as shown below.

Start pre-train phase.
Rest for 0.000 hour:
logs/pre_train/soybean-resnet12
Epoch 1, total loss=5.9711 acc=0.0000: 100%|██| 600/600 [00:17<00:00, 34.51it/s]
  0%|                                                  | 0/3000 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    trainer.pre_train()
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/trainer/meta_trainer.py", line 376, in pre_train
    (data_shot, data_query)) 
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/model/meta_model.py", line 158, in forward
    return self.pretrain_forward(inputs)
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/model/meta_model.py", line 166, in pretrain_forward
    return self.fc(self.encoder(input))
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/model/resnet12.py", line 113, in forward
    x = self.layer1(x)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/model/resnet12.py", line 49, in forward
    out = self.conv1(x)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not tuple

In conclusion, the error is that the model takes tensor as input but a tuple (data_shot, data_query) are given.

In addition, I fould another problem:
When choosing the paratemers to be optimized in the optmizer, the ''self.model' seems incorrect as error occurs, I change 'self.model' to 'self.model.module', it works. 
These errors may caused by the multi-gpu scenerio.
However, when I use only one gpu, an error below occurs,

Start pre-train phase.
Rest for 0.000 hour:
logs/pre_train/soybean-resnet12
Epoch 1, total loss=5.4935 acc=0.0000: 100%|██| 600/600 [00:12<00:00, 46.65it/s]
  0%|                                                  | 0/3000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    trainer.pre_train()
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/trainer/meta_trainer.py", line 376, in pre_train
    (data_shot, data_query)) 
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/model/meta_model.py", line 161, in forward
    return self.meta_forward(data_shot, data_query)
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/model/meta_model.py", line 220, in meta_forward
    grad = torch.autograd.grad(loss, fast_weights)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

 I am grateful if you can provide any support to figure out the problem.

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

Please update this line as follows,
https://github.com/yaoyao-liu/e3bm/blob/dd44c9e7769761e0735efb839c5c01b68396d596/trainer/meta_trainer.py#L365

If it doesn't work, please let me know.

Best,
Yaoyao

**Comment by Markin-Wang** [comment]
> Thanks for your interest in our work.
> 
> Please update this line as follows,
> https://github.com/yaoyao-liu/e3bm/blob/dd44c9e7769761e0735efb839c5c01b68396d596/trainer/meta_trainer.py#L365
> 
> If it doesn't work, please let me know.
> 
> Best,
> Yaoyao

Dear Yaoyao,
Thanks for your early reply.
After modifying the code, another error occurs,

Start pre-train phase.
Rest for 0.000 hour:
logs/pre_train/soybean-resnet12
Epoch 1, total loss=5.2960 acc=0.0000: 100%|██| 600/600 [00:12<00:00, 46.56it/s]
  0%|                                                  | 0/3000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    trainer.pre_train()
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/trainer/meta_trainer.py", line 375, in pre_train
    logits = model.meta_forward(data_shot, data_query)
  File "/home/ubuntu/junwang/paper/bmvc/e3bm/model/meta_model.py", line 220, in meta_forward
    grad = torch.autograd.grad(loss, fast_weights)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

Best Regards,
Jun

**Comment by yaoyao-liu** [comment]
Thanks for the feedback.
I have updated the related code, and now you can try it.

I don't have time to test this project today. Maybe I can do it on Monday or Tuesday. I'll let you know when we have tested the pre-train code. You may also directly download the pre-trained model and start the meta-train phase.

**Comment by Markin-Wang** [comment]
> Thanks for the feedback.
> I have updated the related code, and now you can try it.
> 
> I don't have time to test this project today. Maybe I can do it on Monday or Tuesday. I'll let you know when we have tested the pre-train code. You may also directly download the pre-trained model and start the meta-train phase.

Thanks for your reply.
I updated the code and still got an error shown below:

`
Epoch 1, total loss=4.9012 acc=0.0000: 100%|██| 600/600 [00:13<00:00, 45.70it/s]
  0%|                                                  | 0/3000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    trainer.pre_train()
  File "e3bm/trainer/meta_trainer.py", line 372, in pre_train
    logits = model.meta_forward(data_shot, data_query)
  File "e3bm/model/meta_model.py", line 221, in meta_forward
    generated_combination_weights = self.hyperprior_combination_model(embedding_shot, grad, k)
  File "/home/ubuntu/anaconda3/envs/bmvc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in 
__getattr__
    type(self).__name__, name))
`
`
AttributeError: 'MetaModel' object has no attribute 'hyperprior_combination_model'
`
Besides, I wonder whether this code supports multi-gpu training?
Thanks for your support.
Jun

**Comment by yaoyao-liu** [comment]
I have updated the code and tested it. I think the pre-training phase is able to run now.
I have never tried it with multiple GPUs. I recommend you run it on a single GPU.

Best,
Yaoyao

**Comment by Markin-Wang** [comment]
> I have updated the code and tested it. I think the pre-training phase is able to run now.
> I have never tried it with multiple GPUs. I recommend you run it on a single GPU.
> 
> Best,
> Yaoyao

Thanks for your kind support, it works now!
Kind Regards,
Jun
